apiVersion: apps/v1
kind: Deployment
metadata:
  name:  router-deployment
  labels:
    name:  router
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  router
  template:
    metadata:
      labels:
        app :  router
    spec:
      containers:
      - image:  router
        name:  router-server
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "250m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "400Mi"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 3000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/readyz
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10   
        ports:
        - containerPort:  3000
          name:  http